//
// Demonstrates simple asynchronous TCPIP Client and Server
//
// Code base partially generated by ChatGPT.
//

using System;
using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;

namespace WDFA01Server
{
    class WDFA01Server
    {

        //object used to do the syncronization 
        private static readonly object locker = new object();
        private static volatile bool stopWriting = false;
        public static async Task Main()
        {


            Int32 port = int.Parse(ConfigurationManager.AppSettings["Port"]);
            string localAddr = (ConfigurationManager.AppSettings["IP"]);

            // Create the TcpListener and start it
            TcpListener listener = new TcpListener(IPAddress.Parse(localAddr), port);
            listener.Start();
            Console.WriteLine("Server started on port");

            // Main loop to handle client requests.
            // The server accepts a client request, then passes control
            //    to the code that does the work.

            while (true)
            {
                TcpClient client = await listener.AcceptTcpClientAsync();
                Task task = HandleClientAsync(client);
            }
        }

        // The client handler handles the request
        private static async Task HandleClientAsync(TcpClient client)
        {
            bool done = false;
            Console.WriteLine("Client connected");

            try
            {
                // The using statement should be used to make communications
                //   easier.
                using NetworkStream stream = client.GetStream();

                while (!done)
                {
                    // Need a buffer for the input
                    byte[] buffer = new byte[1024];

                    int bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length);

                    if (bytesRead == 0)
                    {
                        Console.WriteLine("Client disconnected");
                        break;
                    }

                    // Remember, the data over TCP/IP is in bytes, so the stream
                    //    must be converted to a string so you can use it.
                    string Fullmessage = Encoding.UTF8.GetString(buffer, 0, bytesRead);

                    Console.WriteLine($"Received: {Fullmessage}");

                    // When user type shutdown command
                    if (Fullmessage.Equals("Shutdown", StringComparison.OrdinalIgnoreCase))
                    {
                        string shutdown = "Shutdown command, connection will be closed";
                        byte[] shutdownBytes = Encoding.UTF8.GetBytes(shutdown);
                        await stream.WriteAsync(shutdownBytes, 0, shutdownBytes.Length);
                        client.Close();
                        break;
                    }

                    string[] MessageParts = Fullmessage.Split("|");

                    if (MessageParts.Length != 3)
                    {
                        string badRequest = "Invalid input. Please check the usage";
                        byte[] badRequestBytes = Encoding.UTF8.GetBytes(badRequest);
                        await stream.WriteAsync(badRequestBytes, 0, badRequestBytes.Length);
                        continue;
                    }

                    bool parseClientNo = int.TryParse(MessageParts[0], out int ClientNo);
                    bool parseFileSize = int.TryParse(MessageParts[1], out int FileSize);
                    string Message = MessageParts[2];

                    if (!parseClientNo || !parseFileSize || ClientNo < 1 || FileSize < 1)
                    {
                        string badInt = "Invalid input. Client and File size must be positive integers";
                        byte[] badIntBytes = Encoding.UTF8.GetBytes(badInt);
                        await stream.WriteAsync(badIntBytes, 0, badIntBytes.Length);
                        continue;
                    }


                    string filepath = (ConfigurationManager.AppSettings["File"]);
                    //string filepath = @"E:\SRC\WNP\-WNP-A01-Task-1\WDFA01\text.txt";

                    //EnsureFileExists(filepath);

                    // Run multiple tasks that may throw exceptions
                    await Task.WhenAll(
                        MonnitorFileSize(FileSize, filepath),
                        //Task.Run(() => Writefile(filepath, message)),
                        Setnumberofclients(filepath, Message, ClientNo)
                    );

                    // Wait for all tasks to complete 
                    //task.Wait();



                    // The data must be converted to a byte array to be used
                    //    by TCP/IP
                    string response = "Message received!";
                    byte[] responseBytes = Encoding.UTF8.GetBytes(response);

                    await stream.WriteAsync(responseBytes, 0, responseBytes.Length);
                    Console.WriteLine("Response sent");

                    if (Fullmessage == "Shutdown")
                    {
                        done = true;
                        client.Close();
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
            }
            // Always close socket after handle the request from client
            finally
            {
                client.Close();
            }
        }

        static async Task MonnitorFileSize(int filesize, string filepath)
        {
            for (int i = 0; i < 100; i++)
            {
                // long length = new System.IO.FileInfo(path).Length;
                long length = new FileInfo(filepath).Length;
                Console.WriteLine($"file size: {length}");

                if (length >= filesize)
                {
                    Console.WriteLine("File size Reached...");
                    stopWriting = true;
                    // how to stop async program 
                    break;
                }

                // 10 times check per second
                await Task.Delay(100);
            }
        }

        static void Writefile(string filename, string message)
        {
            // code to write to file
            StreamWriter sw = null;

            lock (locker)
            {
                try
                {
                    using (sw = new StreamWriter(filename, true))
                    {
                        sw.WriteLine(message);
                    }
                }
                catch (Exception ex)
                {

                    Console.WriteLine(ex.Message);
                }

            }
        }

        static async Task Setnumberofclients(string filename, string message, int number)
        {
            // code to set number of clients 
            Task[] clientTasks = new Task[number];

            for (int i = 0; i < number; i++)
            {
                int clientId = i + 1; // for logging
                clientTasks[i] = Task.Run(() =>
                {
                    if (!stopWriting)
                    {
                        Writefile(filename, message);
                    }

                });
            }

            await Task.WhenAll(clientTasks);

            Console.WriteLine("All clients have written their messages.");
        }
    }


}
